### ISSUE TITLE
change start_join to retry_join

### ISSUE THREAD

**Issue by discointheair** [ansible-collections/ansible-consul#101]
Hi
If there are no knowing drawbacks at your site I would suggest changing “start_join” to “retry_join” in config.json.j2. I have problems to deploy a new cluster without using retry, because not all nodes start simultaneously.

**Comment by brianshumate** [comment]
Hi there,

This is a good suggestion and I'll implement that shortly. Thanks!

**Comment by brianshumate** [comment]
This is changed in 17450be and a new release will be made today, so I will close this now.
