### ISSUE TITLE
Cannot rerun the role to setup additional nodes

### ISSUE THREAD

**Issue by vincent-legoll** [ansible-collections/ansible-consul#109]
I ran the role once to setup a node, then added a new node in inventory and re-ran the playbook.

It failed because of the combination of:
- when clause skipped the node I had already setup on the first run (that host, even if skipped counts for the run once)
- run_once ensured that the download tasks are not run on the new node
- the cleanup action from the previous run removed the downloaded file

Error:
```
TASK [ansible-consul : Install Consul] *******************************************************************************************************************************************************
skipping: [192.168.1.200]
fatal: [192.168.1.111]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/home/vlegoll/dev/ansible/roles/ansible-consul-brianshumate/files/consul' in expected paths."}
```

At least this should be documented, IMHO.

Commenting out the first (succesful node from the inventory) made the new node download and install OK...

**Comment by vincent-legoll** [comment]
I've not retried, but I think the above is not the only reason this role should be run only once on all the nodes.

I remember having a problem with encryption keys not being re-propagated on all the nodes if run a second time.

**Comment by groggemans** [comment]
It did work in the past, so this might be a regression. Although it's not the prime focus of the role, I do find it important an Ansible role is idempotent and can be run multiple times.

If you have any clues please do report them!

**Comment by discointheair** [comment]
I can also support here end of next week. 
I believe I need to set a static encryption keys so be able to rerun the script for the same nodes multiple times. Don't tested to increase the nodes with existing nodes before.

**Comment by groggemans** [comment]
If you also target existing server nodes, the key should be retrieved automatically. If you're running against a single client or unconfigured server only, the encryption key needs to be provided.

**Comment by discointheair** [comment]
@vincent-legoll 
Were you able to add new nodes now?

**Comment by vincent-legoll** [comment]
Yes, but it was only a simple/quick test, nothing thorough enough.

**Comment by groggemans** [comment]
@vincent-legoll Dit it work in a large test? Can we close this issue?

**Comment by vincent-legoll** [comment]
No time for now. Close it if you want
