### ISSUE TITLE
How To Set a recursor

### ISSUE THREAD

**Issue by akamalov** [ansible-collections/ansible-consul#118]
Greetings!!

Can anyone give me a hint on how to use a recursor ? I tried to set recursor list using:

```
--extra-vars "consul_recursors=192.168.96.245,192.168.96.212,192.168.96.234" 
```
However, it's not working, because it is getting parsed i config.json in the following manner:

```
"recursors": [
"1",
"9",
"2",
"."
...
```
Any hints ?

Thanks again!!

**Comment by rkgyellowjacket** [comment]
So the recursors are taken in as a list, each ip being an element of it.
>... --extra-vars "consul_recursors=['192.X', '192.Y', '192.Z']"

That should work, or put single quotes around each element.

**Comment by akamalov** [comment]
Thanks so much @rkgyellowjacket

**Comment by groggemans** [comment]
@rkgyellowjacket Thank you for helping out!

**Comment by akamalov** [comment]
The same result @rkgyellowjacket. Here is the directive I am issuing (this time I tried to configure for dnmasq):

```
--extra-vars "consul_dnsmasq_servers='192.168.96.245','192.168.96.212','192.168.96.234']"
```

The output of **/etc/dnsmasq.d/10-consul**:

```
--extra-vars "consul_dnsmasq_servers='192.168.96.245','192.168.96.212','192.168.96.234']"

server='
server=1
server=9
server=2
server=.
server=1
server=6
server=8
server=.
server=9
server=6
server=.
server=2
server=4
server=5
server='
server=,
```
Very weird :(

**Comment by groggemans** [comment]
@akamalov You should have a look at the ansible docs; http://docs.ansible.com/ansible/latest/playbooks_variables.html#passing-variables-on-the-command-line

You might wan't to give json formatted extra vars a try for more complex data types. I also advice you to make use of the host and group variables. Or set these in your sites.yml or a separate vars file that you include. It will make things a lot simpler!

**Comment by akamalov** [comment]
Thanks @groggemans!!!
