### ISSUE TITLE
Optional gossip broken if turned on consul_encrypt_enable (which is default to be true)

### ISSUE THREAD

**Issue by chrisparnin** [ansible-collections/ansible-consul#132]
Recently, code was changed make the encrypt setting in config.json `consul keygen` optional:

```diff
-    "encrypt": "{{ consul_raw_key }}",
+    {% if consul_encrypt_enable %}
+        "encrypt": "no key",
+    {% endif %}
```
https://github.com/brianshumate/ansible-consul/commit/11a554941ff05dba99146909e30e5f796473036c#diff-ca5bb9e516febbc560d531ce7f8b87e3L63

As a result, this caused the role to fail in ansible scripts we previously had working. This causes consul to fail to startup with the following error message: ["encrypt has invalid key: illegal base64 data at input byte..."](https://github.com/hashicorp/consul/blob/master/agent/config/runtime_test.go#L1807)

A workaround is to turn this off:
```
    - role: brianshumate.consul
      consul_encrypt_enable: false
```

But shouldn't the correct code be?
```
    {% if consul_encrypt_enable %}
        "encrypt": "{{ consul_raw_key }}",
    {% endif %}
```

**Comment by groggemans** [comment]
Thanks for the great report, would you like to provide a PR yourself?

**Comment by chrisparnin** [comment]
I could try this fix, but I wasn't sure of the over nature/goal of the change. Let me know if this seems right.

**Comment by groggemans** [comment]
Your fix looks correct to me :+1: (I'll double check just to be sure -> fix should be good)

**Comment by brianshumate** [comment]
Hey @chrisparnin, Thanks for catching this and we're happy yo accepted a pull request if you'd like to tee one up!

**Comment by chrisparnin** [comment]
Tested fix locally on new nomad cluster and it appears to work correctly.
Pull request: https://github.com/brianshumate/ansible-consul/pull/134

**Comment by groggemans** [comment]
Thank you!
