### ISSUE TITLE
Gossip key writing isn't idempotent

### ISSUE THREAD

**Issue by mattburgess** [ansible-collections/ansible-consul#136]
My ansible runs are showing the 2 tasks "Write gossip encryption key locally for use with new servers" and "Delete gossip encryption key file" as changing on every Ansible run.  I can't see an obvious conditional to place in the 'when' to prevent them from running.  As it's just a temporary file that's being written to and deleted, is it too much of a lie to put a 'changed_when: false' line in to each task?  I only ask because I get a bit nervous when the summary line shows more things having changed than I initially expected on any given run.

**Comment by groggemans** [comment]
As there's nothing changing on the servers/clients for these steps, I agree that we should add `changed_when: false`. Would you like to provide a PR yourself?

**Comment by mattburgess** [comment]
Sure #137 opened.  Thanks!
