### ISSUE TITLE
templates/config.json.j2   "encrypt": "no key"

### ISSUE THREAD

**Issue by discointheair** [ansible-collections/ansible-consul#139]
Hi 

Could you please implement an (optional) key to set  the encrypt  key? 

Proposal:

    {## Encryption and TLS ##}
    {% if consul_encrypt_enable %}
        "encrypt": "{{ consul_encytpt_key }}",
    {% endif %}

**Comment by ChrisMcKee** [comment]
This appears to already exist; so the ticket can close?

```
    {## Encryption and TLS ##}
    {% if consul_encrypt_enable %}
    "encrypt": "{{ consul_raw_key }}",
    {% endif %}
```

**Comment by groggemans** [comment]
@ChrisMcKee thanks for checking!

It's missing in the `README`, so we should add this to the documentation before closing.

**Comment by ChrisMcKee** [comment]
@groggemans PR boom 😉

**Comment by groggemans** [comment]
@ChrisMcKee Awesome!

**Comment by groggemans** [comment]
Thx @ChrisMcKee

**Comment by discointheair** [comment]
Hi 
Thank you. 
config.json.j2 seems to be ok but "consul_raw_key" seems not to be set set in defaults/main.yml

**Comment by groggemans** [comment]
@discointheair It will be set during the run of the playbook if empty. (Because it will be read from already bootstrapped servers if not provided and enabled)
