### ISSUE TITLE
Role is not idempotent

### ISSUE THREAD

**Issue by kostyrev** [ansible-collections/ansible-consul#14]
Strangely enough, nobody pointed out yet that this role is not idempotent.
with every Ansible run it will:
```TASK [brianshumate.consul : Generate gossip encryption key
TASK [brianshumate.consul : Bootstrap configuration
TASK [brianshumate.consul : Client configuration
TASK [brianshumate.consul : Server configuration
TASK [brianshumate.consul : systemd script
```
not to mention
```TASK [brianshumate.consul : Reconfigure bootstrap node (systemd)```

**Comment by brianshumate** [comment]
Hi,

Indeed, this role was not designed to be run more than once as it is for initial cluster formation only. It does not (yet) deal with anything else such as rolling config changes etc. so it is pointless to run it more than once at this time.

That said, I will eventually add some checks to make it idempotent.

Thanks for the report!

**Comment by brianshumate** [comment]
@kostyrevaa Hi, I added some checks to make the role aware that the cluster has already been bootstrapped so that it does not repeat operations. Can you have a look and let me know if this meets your needs?

Feel free to make any suggestions as well.

**Comment by kostyrev** [comment]
Hello! I've decided to write my own role, so it is not an issue for me any more.
You could check the Idempotence yourself: basically, I just used your [README_VAGRANT.md](https://github.com/brianshumate/ansible-consul/blob/master/examples/README_VAGRANT.md) setup and ran ansible twice.

**Comment by kostyrev** [comment]
Hi Brian!
I confirm that now role is idempotent.
Thanks!
