### ISSUE TITLE
Enhancing syslog logging.

### ISSUE THREAD

**Issue by ykhemani** [ansible-collections/ansible-consul#144]
Hello!

Ownership of {{ consul_log_path }} being {{ consul_user }}:{{ consul_group }} rather than syslog:adm prevents rsyslogd from writing logs in {{ consul_log_path }}.

We would like to be able to define syslog facility used for logging messages. Suggest we define the variable consul_syslog_facility for this purpose.

Also, in order to have rsyslogd write consul logs to {{ consul_log_path }}, we need a corresponding rule to the syslog facility. Suggest that this happens via the /etc/rsyslog.d/00-consul.conf. Alternatively, the path to this file could also be defined via a variable.

I'm happy to make modifications and submit a PR once we agree on the approach.

Please let me know if you have any questions.

Thanks!
-yash

**Comment by brianshumate** [comment]
This sounds like a nice enhancement!

**Comment by brianshumate** [comment]
Closing this since merged.
