### ISSUE TITLE
systemd script not updating due to bootstrap file presence

### ISSUE THREAD

**Issue by mattburgess** [ansible-collections/ansible-consul#155]
https://github.com/brianshumate/ansible-consul/commit/3bcf7f65c30a44034954df71951f7dfab376d25e changed the location of the custom consul configuration file.  That should have caused the systemd unit file to be updated, but due to the guard at https://github.com/brianshumate/ansible-consul/blob/master/tasks/main.yml#L276, as I've already got a bootstrapped consul agent, that didn't happen.  I'd ordinarily raise a PR to fix such a trivial issue, but I'm not so well versed in consul to understand which tasks in that block should/shouldn't be prevented from running on an already bootstrapped node.  My naive approach would be to simply move the opening 'block' from https://github.com/brianshumate/ansible-consul/blob/master/tasks/main.yml#L175 to https://github.com/brianshumate/ansible-consul/blob/master/tasks/main.yml#L245 thus just excluding the creation/update of service start scripts. If that seems sensible I'll get a PR together that handles that as well as fixes up the systemd bit so that it properly reloads the systemctl daemon on a unit-file change.

**Comment by mattburgess** [comment]
OK, after all that waffling on, I realised it's probably just easier to show you the code.  PR at https://github.com/brianshumate/ansible-consul/pull/156.

**Comment by brianshumate** [comment]
Merged code, closing this...
