### ISSUE TITLE
Any idea on how the role can be used with dynamic inventory?

### ISSUE THREAD

**Issue by rabchev** [ansible-collections/ansible-consul#159]
Are dynamic inventories supported, such as Google Compute Engine? I was hoping to be able to tag VM instances with [consul_instance] or something like that. Apparently this doesn't work.

Is there a way to apply the role to all specified hosts without them been in consul_instances group? This would allow me to filter the hosts by other means.

**Comment by rabchev** [comment]
Never mind, I figured it out. I can set [consul_group_name]. 

GCE inventory creates host group for every VM tag, but the problem is that it prefixes the names with "tag_". Changing [consul_group_name] value solves the problem.

**Comment by groggemans** [comment]
Thank you for the updated info, might be useful for other people!
