### ISSUE TITLE
specifying sha256 is not user-friendly

### ISSUE THREAD

**Issue by kostyrev** [ansible-collections/ansible-consul#16]
Hi!
I'd like to propose an enhancement.
It is possible [not to specify sha256 sum](https://github.com/wunzeco/ansible-consul-template/blob/master/tasks/install.yml) for consul zip.
What do you think?

**Comment by brianshumate** [comment]
Hi!

This is a cool approach, and I'll go ahead and throw that in soon.

Thanks!

**Comment by brianshumate** [comment]
Okay, that's in and new release cut.

Thanks again! 😸
