### ISSUE TITLE
is_virtualenv treated as defined when defaulted to empty string

### ISSUE THREAD

**Issue by konraddzyr** [ansible-collections/ansible-consul#161]
Hi All!

Playbook tries to run task "Install netaddr dependency on controlling host (virtualenv)" when varaible VIRTUAL_ENV is not set in VM. Then is_virtualenv is defaulted to '' what is treated as defined value. Then task without user arg is invoked and it results in error caused by lack of permissions on VM.
Connected to [#129](https://github.com/brianshumate/ansible-consul/issues/129)

I'm running role with vagrant 2.0.2 on Win10 against Centos 7 on Virtualbox 5.2.4

**Comment by anshulaa** [comment]
Any hacks for this?

**Comment by brianshumate** [comment]
I am hoping we can just remove the need for installing netaddr to address this.
