### ISSUE TITLE
Regular Release

### ISSUE THREAD

**Issue by GnomeZworc** [ansible-collections/ansible-consul#170]
Please consider doing more regular release to ansible-galaxy

**Comment by brianshumate** [comment]
Hey thanks for the input. I don't really use Ansible much any longer, so I need to get some assistance in maintaining this role or it's likely to be abandoned within the year.

**Comment by groggemans** [comment]
I started helping, but have been busy lately. As I'm still using this role I'll probably keep maintaining it for some time.

@brianshumate I don't think I can make releases on galaxy. So once the time comes you no longer support the role yourself we should have a look at how we can solve this.
