### ISSUE TITLE
How to enable beta ui?

### ISSUE THREAD

**Issue by burkostya** [ansible-collections/ansible-consul#172]
Setting `CONSUL_UI_BETA=true` using
```
environment:
  CONSUL_UI_BETA: true
```
does not work

**Comment by brianshumate** [comment]
Hi, that was just pushed to the v2.0.1 so you'll need to update your role version and it is should then work.

**Comment by burkostya** [comment]
Thanks!

```yaml
consul_env_vars:
  - "CONSUL_UI_BETA=true"
```
works fine
