### ISSUE TITLE
Python 2 is missing from ubuntu/xenial64

### ISSUE THREAD

**Issue by jkevlin** [ansible-collections/ansible-consul#177]
BOX_NAME=ubuntu/xenial64 CONSUL_IFACE=enp0s8 vagrant up --provision

`fatal: [consul1.consul]: FAILED! => {"changed": false, "module_stderr": "Shared connection to consul1.consul closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 127}`

The solution that I found was to install it at the beginning of site.yml
`
- name: dependency provisioning
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      tags: always
`

**Comment by jkevlin** [comment]
A more portable solution
`
if [ -f "/etc/debian_version" ]; then
  test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
fi
`

**Comment by brianshumate** [comment]
Hey there,

Thanks for the ideas here, but I'm afraid that the proposed changes to this project are too specific for something that can be worked around by instead switching Vagrant boxes.

I don't recommend using Ubuntu official Vagrant boxes as they've been historically problematic and are also ironically enough, not good idiomatic examples of an Ubuntu Vagrant box.

With that said, you can simply use a different box that does include Python 2, such as the `bento/ubuntu-16.04` box. [Bento Boxes](https://app.vagrantup.com/bento) are good representations of how to build proper Vagrant boxes. I think the official Ubuntu boxes are improving, but not sure about older versions such as 16.04.

This works fine for me with the role as-is, for example:

```
BOX_NAME=bento/ubuntu-16.04 vagrant up
```

I'm going to close this in favor of recommending different boxes for problems of this type.

**Comment by jkevlin** [comment]
Thank you for reviewing my pr's, I will try your suggestion to use bento/ubuntu-16.04.
-john
 
 
----- Original message -----From: Brian Shumate <notifications@github.com>To: brianshumate/ansible-consul <ansible-consul@noreply.github.com>Cc: John Kevlin <jkevlin@ibm.com>, Author <author@noreply.github.com>Subject: Re: [brianshumate/ansible-consul] Python 2 is missing from ubuntu/xenial64 (#177)Date: Mon, Jul 9, 2018 9:25 AM 
Hey there,
Thanks for the ideas here, but I'm afraid that the proposed changes to this project are too specific for something that can be worked around by instead switching Vagrant boxes.
I don't recommend using Ubuntu official Vagrant boxes as they've been historically problematic and are also ironically enough, not good idiomatic examples of an Ubuntu Vagrant box.
With that said, you can simply use a different box that does include Python 2, such as the bento/ubuntu-16.04 box. Bento Boxes are good representations of how to build proper Vagrant boxes. I think the official Ubuntu boxes are improving, but not sure about older versions such as 16.04.
This works fine for me with the role as-is, for example:
BOX_NAME=bento/ubuntu-16.04 vagrant up
I'm going to close this in favor of recommending different boxes for problems of this type.
