### ISSUE TITLE
Update Ansible Galaxy to 1.2.2

### ISSUE THREAD

**Issue by nathkn** [ansible-collections/ansible-consul#188]
The role on Ansible Galaxy is still set to 1.1.0 and it would be helpful to update it

**Comment by brianshumate** [comment]
Hey there,

Ansible Galaxy was recently updated and I was unable to get it to even recognize my projects when it even worked at all. This was something that used to work well, but I will try to get it updated again.

**Comment by brianshumate** [comment]
Fixed in version 2.0.6 which installs Consul v1.2.2
