### ISSUE TITLE
cannot install unzip

### ISSUE THREAD

**Issue by replicajune** [ansible-collections/ansible-consul#189]
Hello,

When the role try to install unzip in my setup it fails.

in the install.yml file, at line ~60, the role tries to install unzip, it fails. here is part of the error log :

```
...WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory\nWARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory\nERROR: unsatisfiable constraints:\n", "stderr_lines": ["WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory", "WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory", "ERROR: unsatisfiable constraints:"], "stdout": "  unzip (missing):\n    required by: world[unzip]\n", "stdout_lines": ["  unzip (missing):", "    required by: world[unzip]"]}
```
The role seems to fail because the package manager was not being asked to be refreshed.

For me, the problem appear because I'm using ansible in a container (based on alpine), and it cannot found unzip because apk is not initialized.

To fix this, some tasks should be set before this one to refresh some packages managers.

I've already identified a couple of module to work with to fix this problem (I've base my research to supported systems) : 
https://docs.ansible.com/ansible/latest/modules/apk_module.html#apk-module
https://docs.ansible.com/ansible/latest/modules/apt_module.html#apt-module
https://docs.ansible.com/ansible/latest/modules/yum_module.html#yum-module
https://docs.ansible.com/ansible/latest/modules/pkgng_module.html#pkgng-module (not sure)

I'm assuming windows wont have this problem because there's not any package manager

if this bug seems to be worth fixing for you I can provide a pr based on tasks that would refresh apk, apt, yum and pkgng.

is it ok ? :smiley:

**Comment by brianshumate** [comment]
Hi there,

Thanks for the report, but is not a bug; this role does not explicitly support Alpine Linux and so it cannot be expected to function properly in that environment.

The distributions which are supported (RHEL/Debian based) and their associated package managers do not exhibit this issue.

If you'd like to do a PR to add the package repository refreshing step and set it to be conditional on the Alpine distribution only, I can merge it in.

**Comment by replicajune** [comment]
rhel and debian can have this issue if references of packages are outdated (should not happen on base repositories though :) )

i'll submit a PR asap with the conditions you asked

**Comment by replicajune** [comment]
Alright,

The first commit didn't work, the second use lookup and fixed the issue.
However, our team struggled with another error at the end of the role :

```
fatal: [...]: FAILED! => {"msg": "The conditional check '(consul_ports.http|int > -1) and (consul_addresses.http|ipaddr)' failed. The error was: The ipaddr filter requires python-netaddr be installed on the ansible controller\n\nThe error appears to have been in '/ansible/playbooks/roles/consul/tasks/main.yml': line 259, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Check Consul HTTP API (via TCP socket)\n        ^ here\n"}
fatal: [...]: FAILED! => {"msg": "The conditional check '(consul_ports.http|int > -1) and (consul_addresses.http|ipaddr)' failed. The error was: The ipaddr filter requires python-netaddr be installed on the ansible controller\n\nThe error appears to have been in '/ansible/playbooks/roles/consul/tasks/main.yml': line 259, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Check Consul HTTP API (via TCP socket)\n        ^ here\n"}
fatal: [...]: FAILED! => {"msg": "The conditional check '(consul_ports.http|int > -1) and (consul_addresses.http|ipaddr)' failed. The error was: The ipaddr filter requires python-netaddr be installed on the ansible controller\n\nThe error appears to have been in '/ansible/playbooks/roles/consul/tasks/main.yml': line 259, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Check Consul HTTP API (via TCP socket)\n        ^ here\n"}
```

It's strange because the python dependency is installed on the host right at the beginning of the role.
We didn't go any further as we were short on time and switched over a couple of docker instances

I'll make a PR nonetheless because the first issue is fixed but feel free to refuse it as we were not able to have a working solution in the end.
