### ISSUE TITLE
Ubuntu Trusty (14.04) support

### ISSUE THREAD

**Issue by violuke** [ansible-collections/ansible-consul#19]
The galaxy page says that Trusty is supported, but Trusty still uses upstart and upstart support has been removed from this role. Full support for systemd on Ubuntu started with version 15.04, see [here](https://wiki.ubuntu.com/SystemdForUpstartUsers).

**Comment by brianshumate** [comment]
Hi Luke,

Indeed, Trusty can use upstart, but also still uses the old SysV init script; this init script did work at one time, but appears to have some issue with it now. I am still working with it and testing when I can.

That said, my focus with this role is on more recent OS distributions, which have all (for better or worse) gone to systemd. 😄

**Comment by violuke** [comment]
Hi Brian,

Ok, yes, I see. I'm actually using 16.04 so it's ok for me, but I was just thinking that people might try to use it and find it fails, maybe the ansible-galaxy file should be updated for the time being?
