### ISSUE TITLE
consul_join contains undefined values causing jinja error

### ISSUE THREAD

**Issue by ADeane6** [ansible-collections/ansible-consul#195]
Where running this role with multiple servers defined under consul_instances, consul_join only populates current server ip and undefined for any other ones. This causes the config file to fail on creation

    [u'10.0.0.182', Undefined, Undefined]

From the looks of it the hostvars of the other servers in consul_instance haven't been set correctly as they don't contain the bind address or advertise address (The defaults aren't being picked up)

I thought this could have been an issue with `consul_gather_server_facts` being disabled but changing that didn't help

Hosts

    ####################
    ## consul servers ##
    ####################
    [consul_instances]
    10.0.0.182 consul_node_role=server consul_bootstrap_expect=true
    10.0.0.183 consul_node_role=server consul_bootstrap_expect=true
    10.0.0.184 consul_node_role=server consul_bootstrap_expect=true

Vars file

    consul_install_dependencies: no
    consul_client_address: 0.0.0.0
    consul_gather_server_facts: yes

Playbook

    - name: configure server and deploy consul cluster
      hosts: consul_instances
      serial: 1

      become: yes
      become_user: root

      vars:
        app_name: consul

      vars_files:
        - "environments/{{ env }}/vars/{{ app_name }}"
    
      roles:
        - brianshumate/ansible-consul

Any thoughts on what the issue could be

Also it seems that the encryption key for the gossip protocol isn't being copied between the servers, a new one is being created each time

**Comment by ghost** [comment]
I have some issue in creating configuration. Do you see the same?

`fatal: [prom3.linuxseed.com]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: no filter named 'map'. String: {# This template will be passed through the 'to_nice_json' filter #}\n{# The filter fixes whitespace, indentation and comma's on the last item #}\n{\n    {# Common Settings #}\n\n`

**Comment by ADeane6** [comment]
@linuxsavior That error seems a bit different, The error around the jinja template we get is to do with a json object being undefined.

**Comment by brianshumate** [comment]
@linuxsavior I think your issue is due to the missing `netaddr` package which is typically installed on the Ansible host in order to use the [ipaddr](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_filters_ipaddr.html) filtering.

The role should install it in either a systemwide environment (with `--user`) or in a virtualenv, but if it fails to do so then you should try manually installing `netaddr` with:

```
$ pip install netaddr
```

and that should allow the role to function.

**Comment by ghost** [comment]
Sorry for the delay. Yea, my issue looks to be related to ansible 2.2 version. I upgraded to 2.6 and everything works normal. Sorry for the confusion.

**Comment by brianshumate** [comment]
Good point to know that it is due to the older version, thanks. We do publish a tested version, and the Galaxy role depends on a current version so that issue is not commonly observed.

**Comment by brianshumate** [comment]
Going to close this since it seemed related to Ansible version
