### ISSUE TITLE
Tag 2.0.7 has Alpine check issues on CentOS hosts

### ISSUE THREAD

**Issue by jeffWelling** [ansible-collections/ansible-consul#202]
I've created 3 CentOS hosts and am using the 2.0.7 tag of this repo, but trying to run the ansible playbook against those host causes this error:

```
TASK [brianshumate.consul : Update alpine package manager (apk)] ************************************************************************************************
 [WARNING]: Unable to find '/etc/alpine-release' in expected paths (use -vvvvv to see paths)

fatal: [$HOSTNAME]: FAILED! => {"msg": "The conditional check 'lookup('file','/etc/alpine-release')' failed. The error was: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /etc/alpine-release\n\nThe error appears to have been in '/home/$USER/.ansible/roles/brianshumate.consul/tasks/install.yml': line 60, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Update alpine package manager (apk)\n  ^ here\n"}
```

I'm using the 2.0.7 tag, but this is fixed in install.yml currently in the master branch.

Could you please create a 2.0.8 release with the latest fix at your earliest convenience?
Thanks kindly!

**Comment by dereknex** [comment]
I have same problem. OS is debian.

**Comment by ik234** [comment]
on Ubuntu 16.04 same error i have to comment out the following lines in tasks/install.yml file:
#- name: Update alpine package manager (apk)
#  local_action:
#    module: apk
#    update_cache: yes
#  run_once: true
#  when: lookup('file','/etc/alpine-release')

**Comment by brianshumate** [comment]
Version 2.0.8 is available and fixes this.
