### ISSUE TITLE
Templating config.json fails if --limit is used in playbook

### ISSUE THREAD

**Issue by zswanson** [ansible-collections/ansible-consul#206]
If the role is applied with host limits against the playbook (--limit myhost1) the role fails with the below error. After some testing I believe this is because it cannot access the hostvars of any host not in the play.  This becomes an issue when the consul role is applied as part of a larger playbook for all the inventory and roles/tasks, and a particular host needs to be isolated.

[edit] Using role v2.0.9 with consul v1.2.2. I also tested using the **consul_gather_server_facts**  variable set to 'true' and while task "Gather facts from other servers" did execute, the template still failed with the same error. Oddly, I can see from the verbose output of that task that it did in fact gather facts from the other 2 servers.

> TASK [brianshumate.consul : Create configuration] ***************************************************************************
fatal: [insightosctrl.cluster1]: FAILED! =>
  msg: |-
    An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({# This template will be passed through the 'to_nice_json' filter #}
**... [entire contents of config.json.j2 printed] ...**
    ): Undefined is not JSON serializable

Inventory snippet:
```
[consul_instances]
myhost1 consul_node_role=bootstrap
myhost2 consul_node_role=server
myhost3 consul_node_role=server
```
Sample playbook:
```
- hosts: consul_instances
  become: true
  gather_facts: true
  strategy: linear
  roles:
    - brianshumate.consul
```

Role completes successfully when applied with:
```
ansible-playbook consul.yml
```
Role fails on the confg templating step when applied with
```
ansible-playbook consul.yml --limit=myhost1
```

**Comment by brianshumate** [comment]
Hey there, limit does not work properly in this role as it is designed more for bootstrapping Consul than for ongoing maintenance.

There's a note specifically about this in the [Requirements documentation](https://github.com/brianshumate/ansible-consul/blob/master/README.md#requirements)

**Comment by zswanson** [comment]
Ok looks I just missed that in the requirements Readme. We'll break the
role over to a standalone playbook.

**Comment by brianshumate** [comment]
Cool, sorry about that! I'll go ahead and close this.

**Comment by rlanyi** [comment]
My observation is that it only fails if the limit contains a specific host but it works if your limit is the group itself that contains the consul hosts. (E.g. `--limit consul_instances`.) This way it's possible to skip other hosts that don't need consul to be installed.

**Comment by rgarrigue** [comment]
Just another example of this issue.

Everything was working fine for me, with some vars in group_vars/all.yml, development.yml & so on, plus a couple of vars in the servers's playbook. Running this servers playbook and others with --limit, everything went fine.

Then I moved the vars from the playbook in a group_vars/consul_instance.yml, :boom: . It appears the cullprit is moving the `consul_node_role: server`. Just this one, `consul_bootstrap_expect*` were fine.
