### ISSUE TITLE
Is there a way to use `consul keygen` & `encrypt`?

### ISSUE THREAD

**Issue by jmvbxx** [ansible-collections/ansible-consul#23]
Hi, Brian;

I love this role and I've used it quite a bit both for learning and in production. I'm in the process of switching over to TLS but for the short term is there a way to use the `encrypt` value in the config?

My current config looks like this:
```
{
    "bootstrap": true,
    "server": true,
    "datacenter": "stuff",
    "data_dir": "/var/consul",
    "encrypt": "QyYc0lVJXcNl3idBPREjIYww==",
    "log_level": "INFO",
    "statsd_addr": "127.0.0.1:8125",
    "enable_syslog": true,
    "start_join": ["consul2.server.prod", "consul3.server.prod"]
}
```

Thanks in advance!

**Comment by brianshumate** [comment]
Hi Jason,

Thanks for the kind words!

I am not sure I understand your request here; it sounds like you might be conflating the difference between the RPC API encryption (the `encrypt` configuration option) and TLS, which is only used for the HTTP API. These are separate forms of encryption and both must be used to provide complete encryption of all network traffic.

The role already supports TLS encryption of the HTTP API in a separate configuration file as it is a bit easier to maintain features as separate files. Consul then reads them all in from the configuration directory and applies them to the agent configuration at runtime.

If you could clarify a bit about what you need to achieve, I'd be happy to help.

Cheers and Happy New Year!

**Comment by jmvbxx** [comment]
Thanks for the reply, Brian.

You're absolutely right. TLS is a much better option and certainly the way
to go. I've updated my ansible role to generate the cert if it's not found
and drop it in place .. Or use an existing if it's found.

**Comment by brianshumate** [comment]
Hey Jason,

Sounds good. I am going to go ahead and close this issue now.
