### ISSUE TITLE
Enable syslog logging without adding rsyslogd configuration

### ISSUE THREAD

**Issue by sgrimm-sg** [ansible-collections/ansible-consul#232]
Turning on `consul_syslog_enable` does three things: configures Consul to log to syslog, configures rsyslogd to write Consul logs to a dedicated logfile, and creates the directory for the logfile.

It should be possible to do just the "configure Consul" part of that without the other parts, to support installations where rsyslogd is configured to forward log messages to a central log server instead of writing to local files (or where the sysadmin prefers to combine all syslog logs into a single local logfile).

**Comment by brianshumate** [comment]
Going to close this one since your PR was merged and is now part of a release. Thanks!
