### ISSUE TITLE
Ansible prompts for sudo password if restricting tasks

### ISSUE THREAD

**Issue by sgrimm-sg** [ansible-collections/ansible-consul#234]
If I add a tag to the role when I include it in my playbook, and then try to execute it using `ansible-playbook -t tagname`, it fails in an unexpected way: the local actions complain that they need a sudo password.

This is arguably an Ansible bug, but it turns out to be because I have `ansible_become=true` in my inventory file, and that ends up overriding the `become: false` options on the local tasks because connection options always override task options. Unclear why it only happens when running a subset of tasks, but doesn't happen when running the whole playbook.

But it can be fixed/worked around in the role. The fix is to also override the connection option by changing

```
    become: false
```

to

```
    become: false
    vars:
      ansible_become: false
```

in all the `local_action`s and the tasks with `delegate_to: localhost`.

**Comment by brianshumate** [comment]
Closing this since PR merged. Thanks!
