### ISSUE TITLE
Installing only client agents fails on Create configuration step

### ISSUE THREAD

**Issue by jtexier** [ansible-collections/ansible-consul#250]
Role is working incredibily well to install a cluster of servers but I'm facing an error when I trying to deploy consul on client nodes on a separate playbook than the cluster install. 

I've read that since https://github.com/brianshumate/ansible-consul/pull/116 is possible to use the role that way even it's primarily purpose was to start a cluster. 

My playbook looks like that :  
`
- name: install client
  hosts: "my-client"
  become: true
  environment:
    CONSUL_GROUP_NAME: consul
  vars:
    consul_raw_key: VZSUQqT4ryLNe/g48E5PVg==
    consul_disable_keyring_file: true
  roles:
  - brianshumate.consul
`

The error I get is at the "Create configuration" step and log (even in -vvvv mode) is not enough clear to me to find the solution. 

`
TASK [brianshumate.consul : Create configuration] ***************************************************************************************
fatal: [my-client]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({# This template will be passed through the 'to_nice_json' filter #}\n{# The filter fixes whitespace, indentation and comma's on the last item #}\n{\n    {# Common Settings #}\n\n {## Node ##}\n    \"node_name\": \"{{ consul_node_name }}\",\n    \"datacenter\": \"{{ consul_datacenter }}\",\n    \"domain\": \"{{ consul_domain }}\",\n    {% if consul_version is version_compare('0.7.3', '>=') and consul_node_meta | length > 0 %}\n    \"node_meta\": {{consul_node_meta | default({})| to_json }},\n    {% endif %}\n    {# Performance Settings #}\n    \"performance\": {{ consul_performance| to_json }},\n\n    {## Addresses ##}\n    \"bind_addr\": \"{{ consul_bind_address }}\",\n    \"advertise_addr\": \"{{ consul_advertise_address }}\",\n    \"advertise_addr_wan\": \"{{ consul_advertise_address_wan }}\",\n    \"client_addr\": \"{{ consul_client_address }}\",\n    \"addresses\": {\n        {% if consul_version is version_compare('0.8.0', '<') %}\n            \"rpc\": \"{{ consul_addresses.rpc}}\",\n        {% endif %}\n        \"dns\": \"{{ consul_addresses.dns }}\",\n        \"http\": \"{{ consul_addresses.http }}\",\n \"https\": \"{{ consul_addresses.https }}\",\n        {% if consul_version is version_compare('1.3.0', '>=') %}\n        \"grpc\": \"{{consul_addresses.grpc }}\"\n        {% endif %}\n    },\n    {## Ports Used ##}\n    \"ports\": {\n        {% if consul_version is version_compare('0.8.0', '<') %}\n        \"rpc\": {{ consul_ports.rpc}},\n        {% endif %}\n        \"dns\": {{ consul_ports.dns }},\n   \"http\": {{ consul_ports.http }},\n        \"https\": {{ consul_ports.https }},\n        \"serf_lan\": {{ consul_ports.serf_lan }},\n        \"serf_wan\": {{ consul_ports.serf_wan }},\n        \"server\": {{ consul_ports.server }},\n        {% if consul_version is version_compare('1.3.0', '>=') %}\n        \"grpc\": {{ consul_ports.grpc }}\n        {% endif %}\n    },\n\n    {## Raft protocol ##}\n    \"raft_protocol\": {{ consul_raft_protocol }},\n\n    {## DNS ##}\n    {% if consul_recursors | length > 0 %}\n        \"recursors\": {{ consul_recursors | to_json }},\n    {% endif %}\n\n    {## Agent ##}\n    \"data_dir\": \"{{ consul_data_path }}\",\n    \"log_level\": \"{{ consul_log_level }}\",\n    \"enable_syslog\": {{ consul_syslog_enable | bool | to_json }},\n    \"syslog_facility\": \"{{ consul_syslog_facility }}\",\n    \"disable_update_check\": {{ consul_disable_update_check | bool | to_json }},\n    \"enable_script_checks\": {{ consul_enable_script_checks | bool | to_json }},\n\n    {## Encryption and TLS ##}\n    {% if consul_encrypt_enable %}\n    \"encrypt\": \"{{ consul_raw_key }}\",\n    {% endif %}\n    {% if consul_disable_keyring_file %}\n    \"disable_keyring_file\": true,\n    {% endif %}\n    {% if consul_tls_enable %}\n    \"ca_file\": \"{{ consul_tls_dir }}/{{ consul_tls_ca_crt }}\",\n    \"cert_file\": \"{{ consul_tls_dir }}/{{ consul_tls_server_crt }}\",\n    \"key_file\": \"{{ consul_tls_dir }}/{{ consul_server_key }}\",\n    \"verify_incoming\": {{ consul_tls_verify_incoming | bool | to_json }},\n    \"verify_outgoing\": {{ consul_tls_verify_outgoing | bool | to_json }},\n    \"verify_incoming_https\": {{consul_tls_verify_incoming_https | bool| to_json }},\n    \"verify_server_hostname\": {{ consul_tls_verify_server_hostname | bool | to_json }},\n    {% endif %}\n\n    {## LAN Join ##}\n    \"retry_interval\": \"{{ consul_retry_interval }}\",\n    \"retry_max\": {{ consul_retry_max | int }},\n\n    \"retry_join\":\n    {% for server in _consul_lan_servers %}\n    {%   set _ = consul_join.append(hostvars[server]['consul_advertise_address'] | default(hostvars[server]['consul_bind_address'])) %}\n    {% endfor %}\n    {{ consul_join | map('ipwrap') | list | to_json }},\n\n    {## Server/Client ##}\n    \"server\": {{ (item.config_version != 'client') | bool | to_json }},\n\n    {# Client Settings #}\n    {% if (item.config_version == 'client') %}\n        {## ACLs ##}\n        {% if consul_acl_enable %}\n            {% if consul_version is version_compare('1.4.0', '>=') %}\n                \"primary_datacenter\": \"{{ consul_acl_datacenter }}\",\n                \"acl\": {\n                    \"enabled\": true,\n                    \"default_policy\": \"{{ consul_acl_default_policy }}\",\n                    \"down_policy\": \"{{ consul_acl_down_policy }}\",\n                    \"token_ttl\": \"{{ consul_acl_ttl }}\",\n                    \"tokens\": {\n                        {% if consul_acl_token | trim != '' %}\n          \"default\": \"{{ consul_acl_token }}\",\n                        {% endif %}\n                        {% if consul_acl_agent_token | trim != '' %}\n                        \"agent\": \"{{ consul_acl_agent_token }}\",\n                        {% endif %}\n                {% if consul_acl_agent_master_token | trim != '' %}\n                        \"agent_master\": \"{{ consul_acl_agent_master_token }}\",\n                        {% endif %}\n                    }\n                },\n            {% else %}\n                {% if consul_acl_token | trim != '' %}\n                \"acl_token\": \"{{ consul_acl_token }}\",\n                {% endif %}\n       {% if consul_acl_agent_token | trim != '' %}\n                \"acl_agent_token\": \"{{ consul_acl_agent_token }}\",\n    {% endif %}\n                {% if consul_acl_agent_master_token | trim != '' %}\n                \"acl_agent_master_token\": \"{{ consul_acl_agent_master_token }}\",\n                {% endif %}\n                \"acl_ttl\": \"{{ consul_acl_ttl }}\",\n                \"acl_datacenter\": \"{{ consul_acl_datacenter }}\",\n                \"acl_down_policy\": \"{{ consul_acl_down_policy }}\",\n{% endif %}\n        {% endif %}\n    {% endif %}\n\n    {# Server Settings #}\n    {% if (item.config_version == 'server') or (item.config_version == 'bootstrap') %}\n\n    {## Bootstrap settings ##}\n    \"bootstrap\": {{ (item.config_version == 'bootstrap') | bool | to_json }},\n    {% if consul_bootstrap_expect and not (item.config_version == 'bootstrap') %}\n        \"bootstrap_expect\": {{ _consul_lan_servercount | int }},\n\n        {## AutoPilot ##}\n        {% if consul_autopilot_enable %}\n        \"autopilot\": {\n            \"cleanup_dead_servers\": {{ consul_autopilot_cleanup_dead_Servers | bool | to_json }},\n            \"last_contact_threshold\": \"{{ consul_autopilot_last_contact_threshold }}\",\n            \"max_trailing_logs\": {{ consul_autopilot_max_trailing_logs }},\n            \"server_stabilization_time\": \"{{ consul_autopilot_server_stabilization_time }}\"{{ ',' if consul_enterprise else '' }}\n            {% if consul_enterprise %}\n            \"redundancy_zone_tag\":  \"{{ consul_autopilot_redundancy_zone_tag }}\",\n            \"disable_upgrade_migration\": {{ consul_autopilot_disable_upgrade_migration | bool | to_json }},\n            \"upgrade_version_tag\": \"{{ consul_autopilot_upgrade_version_tag }}\"\n            {% endif %}\n        },\n        {% endif %}\n\n    {% endif %}\n\n    {## WAN Join ##}\n    \"retry_interval_wan\": \"{{ consul_retry_interval_wan }}\",\n    \"retry_max_wan\": {{ consul_retry_max_wan | int }},\n\n    {% if _consul_wan_servercount | int > 0 %}\n    \"retry_join_wan\":\n    {% for server in _consul_wan_servers %}\n    {%   set _ = consul_join_wan.append(hostvars[server]['consul_advertise_address_wan'] | default(hostvars[server]['consul_bind_address'])) %}\n    {% endfor %}\n    {{ consul_join_wan | map('ipwrap') | list | to_json }},\n    {% endif %}\n\n    {## ACLs ##}\n    {% if consul_acl_enable %}\n        {% if consul_acl_replication_enable | trim != '' %}\n        \"enable_acl_replication\": {{ consul_acl_replication_enable | bool | to_json }},\n   {% endif %}\n        {% if consul_version is version_compare('1.4.0', '>=') %}\n            \"primary_datacenter\": \"{{ consul_acl_datacenter }}\",\n            \"acl\": {\n                \"enabled\": true,\n                \"default_policy\": \"{{ consul_acl_default_policy }}\",\n                \"down_policy\": \"{{ consul_acl_down_policy }}\",\n                \"token_ttl\": \"{{ consul_acl_ttl }}\",\n                \"tokens\": {\n                    {% if consul_acl_token | trim != '' %}\n                    \"default\": \"{{ consul_acl_token }}\",\n                    {% endif %}\n                    {% if consul_acl_agent_token | trim != '' %}\n\"agent\": \"{{ consul_acl_agent_token }}\",\n                    {% endif %}\n                    {% if consul_acl_agent_master_token |trim != '' %}\n                    \"agent_master\": \"{{ consul_acl_agent_master_token }}\",\n                    {% endif %}\n           {% if consul_version is version_compare('0.9.1', '<') or consul_acl_master_token | trim != '' %}\n                    \"master\": \"{{ consul_acl_master_token }}\",\n                    {% endif %}\n                    {% if consul_acl_replication_token | trim != '' %}\n                    \"replication\": \"{{ consul_acl_replication_token }}\",\n                    {% endif %}\n                }\n            },\n        {% else %}\n            {% if consul_acl_token | trim != '' %}\n            \"acl_token\": \"{{ consul_acl_token }}\",\n            {% endif %}\n            {% if consul_acl_agent_token | trim != '' %}\n            \"acl_agent_token\": \"{{ consul_acl_agent_token }}\",\n            {% endif %}\n            {% if consul_acl_agent_master_token | trim != '' %}\n            \"acl_agent_master_token\": \"{{ consul_acl_agent_master_token }}\",\n            {% endif %}\n            \"acl_ttl\": \"{{ consul_acl_ttl }}\",\n         \"acl_datacenter\": \"{{ consul_acl_datacenter }}\",\n            \"acl_down_policy\": \"{{ consul_acl_down_policy }}\",\n      {% if consul_version is version_compare('0.9.1', '<') or\n                        consul_acl_master_token | trim != '' %}\n    \"acl_master_token\": \"{{ consul_acl_master_token }}\",\n            {% endif %}\n            {% if consul_acl_replication_enable |trim != '' %}\n            \"enable_acl_replication\": {{ consul_acl_replication_enable | bool | to_json }},\n            {% endif %}\n          {% if consul_acl_replication_token | trim != '' %}\n            \"acl_replication_token\": \"{{ consul_acl_replication_token }}\",\n            {% endif %}\n            \"acl_default_policy\": \"{{ consul_acl_default_policy }}\",\n        {% endif %}\n    {% endif %}\n    {% endif %}\n\n    {## UI ##}\n    \"ui\": {{ consul_ui | bool | to_json }}\n}\n): Undefined is not JSON serializable"}
`

I've read about the `limit` bug that can cause this message error as well but I'm not using it as the host is forced on the playbook. 

Any idea ?

Regards

Ansible version 2.7.6 with python version = 2.7.12.

**Comment by danielkucera** [comment]
probably related to #206

**Comment by jtexier** [comment]
I don't think so because as mentionned I don't use the limit option.

**Comment by jtexier** [comment]
In fact, several days after my post I've tried the role to install client another time and everything went well.  The most relevant change was to set consul_group_name as a variable and not using environment var.

```
 - name: Install consul client
  hosts: "{{ resource_group }}"
  any_errors_fatal: true

  roles:
    - role: brianshumate.consul
      vars:
        consul_disable_keyring_file: true
        consul_addresses_http: 0.0.0.0
        consul_group_name: my-consul-group
        consul_join: ["10.1.4.4","10.1.4.5","10.1.4.6"]
        consul_raw_key: my-secret
      become: true
```

**Comment by sas1024** [comment]
Have same problem.

If I set `consul_datacenter: dc`
I've got error on Config step.

If I change datacenter to dcccc - all fine :)

Magic?
