### ISSUE TITLE
flush handlers at the end of the main?

### ISSUE THREAD

**Issue by Sispheor** [ansible-collections/ansible-consul#253]
Hi, 
As handlers are PLAY-scoped and not ROLE-scoped on Ansible. It could be a good practice to add a meta flush handler at the end of the main task. 
So we are sure that the DNS config is up for next roles in the play.

What do you think?

**Comment by brianshumate** [comment]
Hey!

Sounds like a good idea to me!

**Comment by bbaassssiiee** [comment]
@Sispheor can this be closed now?

**Comment by Sispheor** [comment]
Yep.
