### ISSUE TITLE
Could not find or access '/tmp/ansible-consul.4Pxb6d/consul' on the Ansible Controller

### ISSUE THREAD

**Issue by MaxRink** [ansible-collections/ansible-consul#274]
The Role fails to run in my Setup. 
Im executiong the role in an kitchen testsetup and i only get until "TASK [brianshumate.consul : Install Consul]"

The exact error is <details><summary>TASK [brianshumate.consul : Install Consul] </summary>
  An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
       fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/ansible-consul.4Pxb6d/consul' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"} 
</details>
       
The previous extracting task "Unarchive Consul package" was successfull though and when i llok diretly at the FS the binary is placed there. 
<details>
  <summary>Complete Output</summary>
  TASK [include_role : {{ ansible_hostname.rsplit('-',2)[0] }}] ******************

       TASK [brianshumate.consul : Install netaddr dependency on controlling host (with --user)] ***
       changed: [localhost -> 127.0.0.1] => {"changed": true, "cmd": ["/usr/local/bin/pip2", "install", "--user", "netaddr"], "name": ["netaddr"], "requirements": null, "state": "present", "stderr": "DEPRECATION: Python 2.7 will reachthe end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.\n", "stderr_lines": ["DEPRECATION: Python 2.7 will reachthe end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7."], "stdout": "Collecting netaddr\n  Downloading https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)\nInstalling collected packages: netaddr\nSuccessfully installed netaddr-0.7.19\n", "stdout_lines": ["Collecting netaddr", "  Downloading https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)", "Installing collected packages: netaddr", "Successfully installed netaddr-0.7.19"], "version": null, "virtualenv": null}

       TASK [brianshumate.consul : Install netaddr dependency on controlling host (virtualenv)] ***
       ok: [localhost -> 127.0.0.1] => {"changed": false, "cmd": ["/usr/local/bin/pip2", "install", "netaddr"], "name": ["netaddr"], "requirements": null, "state": "present", "stderr": "DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.\n", "stderr_lines": ["DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7."], "stdout": "Requirement already satisfied: netaddr in /root/.local/lib/python2.7/site-packages (0.7.19)\n", "stdout_lines": ["Requirement already satisfied: netaddr in /root/.local/lib/python2.7/site-packages (0.7.19)"], "version": null, "virtualenv": null}

       TASK [brianshumate.consul : Check distribution compatibility] ******************
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check CentOS, Red Hat or Oracle Linux version] *****
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check Debian version] ******************************
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check FreeBSD version] *****************************
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check Ubuntu version] ******************************
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check specified ethernet interface] ****************
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check iptables on Red Hat, CentOS or Oracle Linux] ***
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check for both Dnsmasq and iptables enabled] *******
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check for iptables enabled but no recursors] *******
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check consul_group_name is included in groups] *****
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Fail if more than one bootstrap server is defined] ***
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Fail if a bootstrap server is defined and bootstrap_expect is true] ***
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check if unzip is installed] ***********************
       ok: [localhost -> 127.0.0.1] => {"changed": false, "cmd": "command -v unzip -h >/dev/null 2>&1", "delta": "0:00:00.003016", "end": "2019-04-25 13:08:05.989270", "rc": 0, "start": "2019-04-25 13:08:05.986254", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

       TASK [brianshumate.consul : Fail if unzip is not installed on control host] ****
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Include OS-specific variables] *********************
       ok: [localhost] => {"ansible_facts": {"consul_os_packages": ["unzip"]}, "ansible_included_var_files": ["/tmp/kitchen/roles/brianshumate.consul/vars/Debian.yml"], "changed": false}

       TASK [brianshumate.consul : Gather facts from other servers] *******************

       TASK [brianshumate.consul : Expose advertise_address(_wan) datacenter and node_role as facts] ***
       ok: [localhost] => {"ansible_facts": {"consul_advertise_address": "10.0.2.15", "consul_advertise_address_wan": "10.0.2.15", "consul_bind_address": "10.0.2.15", "consul_datacenter": "dc1", "consul_node_role": "client"}, "changed": false}

       TASK [brianshumate.consul : Read bootstrapped state] ***************************
       ok: [localhost] => {"changed": false, "stat": {"exists": false}}

       TASK [brianshumate.consul : Add Consul group] **********************************
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Add Consul user] ***********************************
       changed: [localhost] => {"changed": true, "comment": "Consul user", "create_home": true, "group": 2, "home": "/home/consul", "name": "consul", "shell": "", "state": "present", "system": true, "uid": 998}

       TASK [brianshumate.consul : file] **********************************************
       changed: [localhost] => (item=/etc/consul) => {"changed": true, "gid": 2, "group": "bin", "item": "/etc/consul", "mode": "0700", "owner": "consul", "path": "/etc/consul", "size": 4096, "state": "directory", "uid": 998}
       changed: [localhost] => (item=/etc/consul/consul.d) => {"changed": true, "gid": 2, "group": "bin", "item": "/etc/consul/consul.d", "mode": "0700", "owner": "consul", "path": "/etc/consul/consul.d", "size": 4096, "state": "directory", "uid": 998}
       changed: [localhost] => (item=/var/consul) => {"changed": true, "gid": 2, "group": "bin", "item": "/var/consul", "mode": "0700", "owner": "consul", "path": "/var/consul", "size": 4096, "state": "directory", "uid": 998}

       TASK [brianshumate.consul : file] **********************************************
       changed: [localhost] => {"changed": true, "gid": 2, "group": "bin", "mode": "0750", "owner": "consul", "path": "/var/run/consul", "size": 40, "state": "directory", "uid": 998}

       TASK [brianshumate.consul : Create log directory] ******************************
       changed: [localhost] => (item=/var/log/consul) => {"changed": true, "gid": 4, "group": "adm", "item": "/var/log/consul", "mode": "0755", "owner": "root", "path": "/var/log/consul", "size": 4096, "state": "directory", "uid": 0}

       TASK [brianshumate.consul : Verify binary path] ********************************
       changed: [localhost] => {"changed": true, "gid": 50, "group": "staff", "mode": "0755", "owner": "root", "path": "/usr/local/bin", "size": 4096, "state": "directory", "uid": 0}

       TASK [brianshumate.consul : Create directories on Windows] *********************
       skipping: [localhost] => (item=/etc/consul)  => {"changed": false, "item": "/etc/consul", "skip_reason": "Conditional result was False"}
       skipping: [localhost] => (item=/etc/consul/consul.d)  => {"changed": false, "item": "/etc/consul/consul.d", "skip_reason": "Conditional result was False"}
       skipping: [localhost] => (item=/var/consul)  => {"changed": false, "item": "/var/consul", "skip_reason": "Conditional result was False"}
       skipping: [localhost] => (item=/var/log/consul)  => {"changed": false, "item": "/var/log/consul", "skip_reason": "Conditional result was False"}
       skipping: [localhost] => (item=/usr/local/bin)  => {"changed": false, "item": "/usr/local/bin", "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Check for existing Consul binary] ******************
       ok: [localhost] => {"changed": false, "stat": {"exists": false}}

       TASK [brianshumate.consul : Calculate whether to install consul binary] ********
       ok: [localhost] => {"ansible_facts": {"consul_install_binary": true}, "changed": false}

       TASK [brianshumate.consul : Install OS packages and consul - locally] **********
       included: /tmp/kitchen/roles/brianshumate.consul/tasks/install.yml for localhost

       TASK [brianshumate.consul : Install OS packages] *******************************
       ok: [localhost] => (item=unzip) => {"cache_update_time": 1556197486, "cache_updated": false, "changed": false, "item": "unzip"}

       TASK [brianshumate.consul : Read package checksum file] ************************
       ok: [localhost -> 127.0.0.1] => {"changed": false, "stat": {"exists": false}}

       TASK [brianshumate.consul : Download package checksum file] ********************
       changed: [localhost -> 127.0.0.1] => {"changed": true, "checksum_dest": null, "checksum_src": "b36ef8b08ee17dad4e9cad33aaca66da7e88ef27", "dest": "/tmp/kitchen/roles/brianshumate.consul/files/consul_1.4.4_SHA256SUMS", "gid": 0,"group": "root", "md5sum": "6564f8a695a20009994ebfce663b7236", "mode": "0644", "msg": "OK (1047 bytes)", "owner": "root", "size": 1047, "src": "/root/.ansible/tmp/ansible-moduletmp-1556197688.94-xmbBQm/tmpqJT1g6", "state": "file", "status_code": 200, "uid": 0, "url": "https://releases.hashicorp.com/consul/1.4.4/consul_1.4.4_SHA256SUMS"}

       TASK [brianshumate.consul : Read package checksum] *****************************
       changed: [localhost -> 127.0.0.1] => {"changed": true, "cmd": "grep \"consul_1.4.4_linux_amd64.zip\" \"/tmp/kitchen/roles/brianshumate.consul/files/consul_1.4.4_SHA256SUMS\" | awk '{print $1}'", "delta": "0:00:00.005003", "end": "2019-04-25 13:08:09.227250", "rc": 0, "start": "2019-04-25 13:08:09.222247", "stderr": "", "stderr_lines": [], "stdout": "d3bdf9817c7de9d83426d8c421eb3f37bf82c03c97860ef78fb56e148c4a9765", "stdout_lines": ["d3bdf9817c7de9d83426d8c421eb3f37bf82c03c97860ef78fb56e148c4a9765"]}

       TASK [brianshumate.consul : Check Consul package file] *************************
       ok: [localhost -> 127.0.0.1] => {"changed": false, "stat": {"exists": false}}

       TASK [brianshumate.consul : Download Consul package] ***************************
       changed: [localhost -> 127.0.0.1] => {"changed": true, "checksum_dest": null, "checksum_src": "122f07bba1bb03748f555b1a42e4da10b73148e6", "dest": "/tmp/kitchen/roles/brianshumate.consul/files/consul_1.4.4_linux_amd64.zip", "gid": 0, "group": "root", "md5sum": "d2246c54f7a8fad103799de4f4613572", "mode": "0644", "msg": "OK (34755554 bytes)", "owner": "root", "size": 34755554, "src": "/root/.ansible/tmp/ansible-moduletmp-1556197689.57-LPCpYa/tmpXxg6oP", "state": "file", "status_code": 200, "uid": 0, "url": "https://releases.hashicorp.com/consul/1.4.4/consul_1.4.4_linux_amd64.zip"}

       TASK [brianshumate.consul : Update Alpine Package Manager (APK)] ***************
       skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

       TASK [brianshumate.consul : Create Temporary Directory for Extraction] *********
       changed: [localhost -> 127.0.0.1] => {"changed": true, "gid": 0, "group": "root", "mode": "0700", "owner": "root", "path": "/tmp/ansible-consul.4Pxb6d", "size": 4096, "state": "directory", "uid": 0}

       TASK [brianshumate.consul : Unarchive Consul package] **************************
       changed: [localhost -> 127.0.0.1] => {"changed": true, "dest": "/tmp/ansible-consul.4Pxb6d/", "extract_results": {"cmd": ["/usr/bin/unzip", "-o", "/home/vagrant/.ansible/tmp/ansible-tmp-1556197690.84-223555340233163/source", "-d", "/tmp/ansible-consul.4Pxb6d/"], "err": "", "out": "Archive:  /home/vagrant/.ansible/tmp/ansible-tmp-1556197690.84-223555340233163/source\n  inflating: /tmp/ansible-consul.4Pxb6d/consul  \n", "rc": 0}, "gid": 0, "group": "root", "handler": "ZipArchive", "mode": "0700", "owner": "root", "size": 4096, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1556197690.84-223555340233163/source", "state": "directory", "uid": 0}

       TASK [brianshumate.consul : Install Consul] ************************************
       An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
       fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/ansible-consul.4Pxb6d/consul' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

       RUNNING HANDLER [netdata : netdata_service_restart] ****************************
        to retry, use: --limit @/tmp/kitchen/default.retry

       PLAY RECAP *********************************************************************
       localhost                  : ok=44   changed=23   unreachable=0    failed=1

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <consul-debian-9>.  Please see .kitchen/logs/consul-debian-9.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

</details>

**Comment by af6140** [comment]
is your /tmp mounted as noexec?

**Comment by bbaassssiiee** [comment]
Set `consul_install_remotely: true`
