### ISSUE TITLE
ACL tokens will never be automatically generated

### ISSUE THREAD

**Issue by evilhamsterman** [ansible-collections/ansible-consul#275]
The blocks to read and generate the ACL Master and Replication tokens will never execute because the blocks they run in check if `(consul_acl_master_token is not defined)` which is always false because that is defined in defaults/main.yml at an empty string.

**Comment by brianshumate** [comment]
Hi,

I think the relevant line in `defaults/main.yml` is this:

```
consul_acl_master_token: "{{ lookup('env','CONSUL_ACL_MASTER_TOKEN') | default('', true) }}"
```

This implies it expects to either find it passed in via Ansible Variable from another playbook or as the value to the environment variable named `CONSUL_ACL_MASTER_TOKEN`.

Those blocks should execute if you actually pass the variable value to the role or set the  `CONSUL_ACL_MASTER_TOKEN` environment variable value to the ACL master token.

Is that not the case for you?

**Comment by evilhamsterman** [comment]
It works fine if you pass in the token, but the blocks in https://github.com/brianshumate/ansible-consul/blob/ae67a7b56846a99480156ce694e24d396eed2778/tasks/acl.yml#L4-L20 and https://github.com/brianshumate/ansible-consul/blob/ae67a7b56846a99480156ce694e24d396eed2778/tasks/acl.yml#L22-L36 should run when you don't pass in a value in to either read the value from an existing server or generate a new token automatically. At least that's how it appears it should be to me.

However since the defaults/main.yml sets the master token to an empty string the check to see if those blocks should run will never pass because the variable is defined. My PR changes the check to see if it is undefined or if it is empty. 

Before my PR if you run your role with consul_acl_enable=true but don't pass a master token you will end up with a cluster with acl enabled but not bootstrapped (you have to run `consul acl bootstrap` to get a token), after my pull request you get a cluster with acl fully bootstrapped. It is certainly valid that you may want a cluster in that state so maybe there should be another option to enable that. But for now those blocks of code will never run the way the code is right now.

**Comment by brianshumate** [comment]
Thanks for the clarification!
