### ISSUE TITLE
Idea / Inquiry: Refactor hashi download code to seperate role

### ISSUE THREAD

**Issue by lanefu** [ansible-collections/ansible-consul#287]
just spit-balling here...in case I get a wild hair on a late night.   The download process accross all the hashi tools is pretty much the same.     Do you think there's value in moving that code to its own role / meta role?

The role dependency might be more complex from an end user perspective, but might be a win for maintenance.

Just wanted to know what you think.

**Comment by brianshumate** [comment]
Hey!

This is a neat idea, but I think it could be fine to leave as is now, since it would allow for perhaps easier migration of roles to packages if that ever becomes a mode of binary distribution.
