### ISSUE TITLE
deprecation warnings in Ansible 2.8

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-collections/ansible-consul#293]
TASK [ansible-consul : Daemon reload systemd in case the binaries upgraded] ****
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/install.yml:106
[DEPRECATION WARNING]: evaluating consul_install_upgrade as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
skipping: [server01] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ansible-consul : Cleanup] ************************************************
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/install.yml:114
changed: [server01 -> 127.0.0.1] => {"changed": true, "path": "/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T/ansible-consul.qdt3al9w", "state": "absent"}

TASK [ansible-consul : Install OS packages and consul - remotely] **************
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:49
skipping: [server01] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [ansible-consul : Check for gossip encryption key on previously boostrapped server] ***
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:59
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

skipping: [server01] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [ansible-consul : Deserialize existing configuration] *********************
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:65
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

skipping: [server01] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [ansible-consul : Save gossip encryption key from existing configuration] ***
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:70
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

skipping: [server01] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [ansible-consul : Write gossip encryption key locally for use with new servers] ***
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:82
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

skipping: [server01] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [ansible-consul : Generate gossip encryption key] *************************
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:97
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

changed: [server01] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}

TASK [ansible-consul : Write key locally to share with other nodes] ************
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:101
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

changed: [server01 -> localhost] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": true}

TASK [ansible-consul : Read gossip encryption key for servers that require it] ***
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:116
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

ok: [server01] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [ansible-consul : Delete gossip encryption key file] **********************
task path: /Users/bas/code/hashi_tools/demo/ansible/roles/ansible-consul/tasks/nix.yml:123
[DEPRECATION WARNING]: evaluating consul_encrypt_enable as a bare variable,
this behaviour will go away and you might need to add |bool to the expression
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This
feature will be removed in version 2.12. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: {{
lookup('env','CONSUL_ENCRYPT_ENABLE') | default(true, true) }}

**Comment by brianshumate** [comment]
Thanks for reporting this. It's been addressed for the next release.

**Comment by brianshumate** [comment]
Closing since addressed in latest release.
