### ISSUE TITLE
Cloud auto-joining feature

### ISSUE THREAD

**Issue by ToROxI** [ansible-collections/ansible-consul#303]
Hello!
According to the [Consul documentation](https://www.consul.io/docs/agent/cloud-auto-join.html), auto-joining is possible on the cloud platforms (some of them). But current revision of `templates/config.json.j2` not include this possibility.

**Comment by soloradish** [comment]
You can use `consul_config_custom` var to archive your goals.

```
consul_config_custom:
  retry_join:
  - "provider=aws tag_key=consul-servers tag_value=auto-join"
```

**Comment by ToROxI** [comment]
Thank you for your answer!
Didn't notice this in documentation.
