### ISSUE TITLE
consul hosts must be defined with names not ip's

### ISSUE THREAD

**Issue by piwi3910** [ansible-collections/ansible-consul#337]
if you define your host like:

[consul]
t-consul01  ansible_host=192.168.93.100
t-consul02  ansible_host=192.168.93.101
t-consul03  ansible_host=192.168.93.102
t-consul04  ansible_host=192.168.93.103
t-consul05  ansible_host=192.168.93.104

All is well

if you define your hosts like:

[consul]
192.168.93.100
192.168.93.101
192.168.93.102
192.168.93.103
192.168.93.104

The host would still be seen as servers, but no bootstrap would happen and the template would not generate correctly to find other nodes.

I found this out by accident after moving to a dynamic host inventory script that used ip's as ansible hosts.

**Comment by rfults** [comment]
Confirmed this was the case when running against a set of vagrant machines.  I would get ``connection refused`` and ``No leader`` errors from consul until I switched to using the hostname. 
 Here is my inventory for reference:
```[consul_instances]
docker1 ansible_host=10.10.0.201 ansible_ssh_private_key_file=/home/rfults/docker-swarm-cluster-ubuntu-vagrant/.vagrant/machines/docker1/virtualbox/private_key consul_node_role=bootstrap consul_bind_address=10.10.0.201
docker2 ansible_host=10.10.0.202 ansible_ssh_private_key_file=/home/rfults/docker-swarm-cluster-ubuntu-vagrant/.vagrant/machines/docker2/virtualbox/private_key consul_node_role=server consul_bind_address=10.10.0.202
docker3 ansible_host=10.10.0.203 ansible_ssh_private_key_file=/home/rfults/docker-swarm-cluster-ubuntu-vagrant/.vagrant/machines/docker3/virtualbox/private_key consul_node_role=server consul_bind_address=10.10.0.203
docker4 ansible_host=10.10.0.204 ansible_ssh_private_key_file=/home/rfults/docker-swarm-cluster-ubuntu-vagrant/.vagrant/machines/docker4/virtualbox/private_key consul_node_role=server consul_bind_address=10.10.0.204
docker5 ansible_host=10.10.0.205 ansible_ssh_private_key_file=/home/rfults/docker-swarm-cluster-ubuntu-vagrant/.vagrant/machines/docker5/virtualbox/private_key consul_node_role=server consul_bind_address=10.10.0.205

[consul_instances:vars]
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_user=vagrant
consul_client_address=0.0.0.0
consul_iface=enp0s8
```
Guest OS info:
```vagrant@docker1:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
...
 ```

**Comment by mldmld68** [comment]
Hi

We just encounter the same issue on GCP with a dynamic inventory file
I workaround it by modifying in 
https://github.com/brianshumate/ansible-consul/blob/master/templates/config.json.j2

# consul_node_name: "{{ inventory_hostname_short }}" 
consul_node_name: "{{ ansible_hostname }}"

@brianshumate : what do you think about this suggestion ?

Regards
MLD

**Comment by piwi3910** [comment]
Dell Customer Communication - Confidential

I'm doing something similar, but I'm using the ansible_fact, fqdn hostname and not inventory names.
