### ISSUE TITLE
Ubuntu 14.04 init file

### ISSUE THREAD

**Issue by 4trus** [ansible-collections/ansible-consul#34]
I had some trouble getting the consul service to start up on a 14.04 server, but finally narrowed things down to some quotation problems in consul_debianinit.j2.

First, **${DAEMON_ARGS}** apparently shouldn't be quoted. According to [this post](http://stackoverflow.com/questions/1661193/start-stop-daemon-quoted-arguments-misinterpreted), bash and ksh on Linux will add in extra quotes that mess things up. So this section:
```
start-stop-daemon --start --quiet --pidfile "${PIDFILE}" --exec "${DAEMON}" --chuid "${USER}" --background --make-pidfile -- \
        "${DAEMON_ARGS}" \
        || return 2
```
should become this:
```
start-stop-daemon --start --quiet --pidfile "${PIDFILE}" --exec "${DAEMON}" --chuid "${USER}" --background --make-pidfile -- \
        ${DAEMON_ARGS} \
        || return 2
```

Second, the process check right after that section was missing a tailing quote mark on the pidfile and the user parameter. After I got the first problem fixed, the service would be started correctly but these checks wouldn't run. So this:
``` 
 if ! start-stop-daemon --quiet --stop --test --pidfile "${PIDFILE} --exec "${DAEMON}" --user "${USER}; then
```
should be this:
```
if ! start-stop-daemon --quiet --stop --test --pidfile "${PIDFILE}" --exec "${DAEMON}" --user "${USER}"; then
```

Last, thanks to all of this I found an edge case for the "Consul up?" playbook task where it incorrectly thought the process was running. Checking for the existence of the pidfile does work, except that in my case, the pidfile stuck around even after the consul process exited. Since the DAEMON_ARGS weren't being passed properly, I would just get a "**==> Must specify data directory using -data-dir**" error from consul, and it would immediately exit. I think the pidfile was created because the consul process did technically start properly, but thanks to the immediate exit, it was never removed with a "service consul stop". I don't really have a good way to improve that.

I did test my template changes and was able to successfully deploy to new 14.04 servers. Thanks for the good work, it's made my life easier as I start to learn and roll out consul.

**Comment by 4trus** [comment]
Oh, and the "Install dependencies for configuration by ansible (1/2)" in tasks/client.yml could use an "update_cache: yes" line. That caused a failure on a couple servers where the apt cache apparently didn't update on it's own.

**Comment by brianshumate** [comment]
Hi!

The role does not officially support older OS versions, but I fixed the problems you encountered in [version 1.10.4](https://github.com/brianshumate/ansible-consul/releases/tag/v1.10.4).

Thanks for the great feedback and glad you have found it to be useful.

**Comment by 4trus** [comment]
Glad I could help, and changing to checking the HTTP API port instead of the pidfile was a good idea. I can understand not officially supporting older releases, but I'll take advantage of it while I can. 

I just tried the new version, and the **--user "${USER}"** parameter from my second example still need a trailing quote.

Also, you might consider an ansible variable for the pidfile location, rather than the static "/var/run/${NAME}/${NAME}.pid". I discovered another weird issue on the same 14.04 servers where the /var/run/consul folder doesn't exist after I reboot the server, and is not automatically created upon consul startup. Changing the initscript template line to "**PIDFILE=/var/run/${NAME}.pid**" was the simplest option for me.

**Comment by brianshumate** [comment]
Sorry about that. I have corrected it and also added `mkrundir()` which is a function from the SYS V init script that ensures the `/var/run/consul` exists before starting the process.

Cheers!
