### ISSUE TITLE
Hashicorp support?

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-collections/ansible-consul#365]
Is there a chance to move this role under https://github.com/hashicorp ?

**Comment by brianshumate** [comment]
I'll try to discuss this with the team and follow up.

**Comment by lanefu** [comment]
@brianshumate -- given your recent update to the readme, I'm assuming the team wasn't interested.   

I'm willing to take maintainer duties if that doesn't work out.   feel free to ping me here or on freenet as lanefu

**Comment by bbaassssiiee** [comment]
@brianshumate @lanefu please add me as a collaborator on the consul and vault roles.

**Comment by brianshumate** [comment]
Hi folks! Indeed, these will remain community projects outside of the organization and I am thrilled that you two want to be added as collaborators for now. I'll go ahead and add you both now.

Thanks!

**Comment by lanefu** [comment]
nomad too please... thanks for all your hard working to get us this far @brianshumate

**Comment by brianshumate** [comment]
Thanks to you both for your help and please reach out to me if you would be interested in relocating the roles at some point!

**Comment by bbaassssiiee** [comment]
I have the powers to fork this into https://github.com/ansible-community. I invited you as Admins.  @brianshumate please take a look at the settings:

- https://github.com/ansible-community/ansible-consul/settings
- https://github.com/ansible-community/ansible-vault/settings
- https://github.com/ansible-community/ansible-nomad/settings

If these work well, then archive yours, so issues stay accessible.

**Comment by brianshumate** [comment]
This is great, Bas!

Thanks so much for the thoughtful idea and approach.

Is it better for me to replace my repo with an empty one and a readme explaining the move? I've never had to do this process before so I'm not familiar with archiving a repository.

**Comment by bbaassssiiee** [comment]
There are 2 ways to do it. The first is "transfer ownership", but if you would choose to do that I need to touch base with Greg@ansible, so don't do it now. The way I did this in the past is with archiving, making the repo read-only. As an example look at https://github.com/bbaassssiiee/base_maven which I moved to https://github.com/dockpack/base_maven because of the bus-factor.

**Comment by bbaassssiiee** [comment]
Transfer ownership might help migrate the issues, and that would be a great asset. I'll ask Greg.

**Comment by bbaassssiiee** [comment]
Hi Brian,

Archiving is done on the ’Settings’ page of a repo, it can be undone. In essence it makes a repo read-only so it will silence pull-requests.
I’m not sure if ’Transfer ownership will move the issues.’ I can try tomorrow.  I’m signing off for today, I’m base in The Netherlands.

If John Barker has additional tips, then I guess they’ll be worth considering, he is a hero!

Bas

**Comment by brianshumate** [comment]
This sounds good to me. Once they are transferred, please let me know!

**Comment by bbaassssiiee** [comment]
@brianshumate , you are the current owner, hence only you can issue 'Tranfer ownership' on the settings page of each repo. I tested if this transfers the issues, and the good news is that it works!

As said, I'm not in control of the **ansible-community** organization, I am allowed to fork, but the previous forks should be removed because 'Transfer ownership' is a better option.

Pending cooperation from Greg and John from Ansible, if you  want to be relieved of the burden, you could transfer ownership to the organization **dockpack**, where I have full admin. This would be an intermediate step, I can liaise with ansible-community and take the baton with @lanefu.

**Comment by brianshumate** [comment]
Hey @bbaassssiiee apologies for the delays as I have been offline a bit.

I saw some discussion via issues but am not sure the current status of transfer. Am I able to transfer now to ansible-community or should we use the intermediate step and transfer to dockpack instead?

Can I do the transfer at any time or do we need to coordinate it?

**Comment by bbaassssiiee** [comment]
Brian: Please transfer to ansible-community, and John: please make bbaassssiiee admin.

Bas

**Comment by brianshumate** [comment]
Hmm, I received an error when attempting the first transfer:

``` 
ansible-community/ansible-consul already exists and You don’t have the permission to create public repositories on ansible-community
```

**Comment by bbaassssiiee** [comment]
Please try again. I renamed and archived the forks.

**Comment by brianshumate** [comment]
Okay, tried again and got another, more bizarre error this time; not sure what this means:

```
ansible-community already has a repository in the brianshumate/ansible-consul network and You don’t have the permission to create public repositories on ansible-community
```

Seems to be still blocked by the forks or something more?

**Comment by bbaassssiiee** [comment]
I invited you to dockpack so you can transfer the repos to us...

**Comment by bbaassssiiee** [comment]
John or Greg should delete the forks...

**Comment by brianshumate** [comment]
👍 Okay got them all transferred to dockpack!

**Comment by bbaassssiiee** [comment]
Cool! I'll be in touch with @gregdek and @gundalow about transfering this to https://github.com/ansible-community/. 

The only thing  @gregdek or @gundalow need to do now is to **delete the archived forks I made:** 


- [https://github.com/ansible-community/ansible-consul-old](https://github.com/ansible-community/ansible-consul-old)
- [https://github.com/ansible-community/ansible-nomad-old](https://github.com/ansible-community/ansible-nomad-old)
- [https://github.com/ansible-community/ansible-vault-old](https://github.com/ansible-community/ansible-vault-old)

After that I will transfer ownership from `dockpack` to **ansible-community** and add @lanefu and yourself. 

A transfer will keep all the PRs and issues of the roles. to avoid the troubles like duplication error you reported https://github.com/dockpack/ansible-consul/issues/365#issuecomment-593543994 

Thanks for the great work you did so far @brianshumate !!!

**Comment by brianshumate** [comment]
Thank you all for your help.

Is it okay if I leave the organizations at this point?

**Comment by bbaassssiiee** [comment]
That's OK.

**Comment by gundalow** [comment]
Hi,
I've deleted `ansible-consul-old` and `ansible-vault-old`.
https://github.com/ansible-community/ansible-nomad-old wasn't archived (unlike the other two repos), so I wanted to double check that needs deleting.

**Comment by bbaassssiiee** [comment]
Yes it does need deletion too.

**Comment by gundalow** [comment]
> Yes it does need deletion too.

I'm sure that was the case, just wanted to check. ansible-community/ansible-nomad-old has also been deleted.

1) Does everybody that need admin (or commit) have those powers now?

2) Anything ese I can help with?

**Comment by bbaassssiiee** [comment]
I transfered ownership of the roles. This team needs admin powers but hasn't: hashicorp-tools (I can't see the 'Settings' tab)

Please add @lanefu and @ksatirli to that team. (Only organization owners can send invitations)

**Comment by gundalow** [comment]
I've invited @lanefu and @ksatirli please ensure you have GitHub 2FA enabled and check your email for an invite.

https://github.com/orgs/ansible-community/teams/hashicorp-tools has been given `admin` on the three repos

Should `groggemans` be in that team as well (they currently have `read` on the three repos)

**Comment by bbaassssiiee** [comment]
Yes please

**Comment by ksatirli** [comment]
Thanks @gundalow (and @bbaassssiiee) - I got the invite!

**Comment by gundalow** [comment]
> Yes please

Done

**Comment by bbaassssiiee** [comment]
Thanks to all!

**Comment by gardar** [comment]
It seems that the role is still on galaxy under the @brianshumate account [brianshumate.consul](https://galaxy.ansible.com/brianshumate/consul) and the "about" section for this github repo points to the url https://galaxy.ansible.com/ansible-community/consul/ which is doesn't exist.
Would be good if this could be fixed as it's a bit confusing right now.

**Comment by lanefu** [comment]
@gardar I've sent a request to get ansible-community organization added to ansible galaxy..

**Comment by gundalow** [comment]
> @gardar I've sent a request to get ansible-community organization added to ansible galaxy..

@lanefu Apporved
