### ISSUE TITLE
Repository moved ? 

### ISSUE THREAD

**Issue by rgarrigue** [ansible-collections/ansible-consul#387]
Hi there

I see this repo moved from brianshumate's to ansible-community. Can we have a word on this in the readme ? Especially, do we still use `brianshumate.consul` for installation ?

Best regards

**Comment by smutel** [comment]
Another thing is to know if this repo is still maintained.
I created a merge request 20 days ago, I did't receive any answer or comment :open_mouth:

**Comment by lanefu** [comment]
> Another thing is to know if this repo is still maintained.
> I created a merge request 20 days ago, I did't receive any answer or comment 😮

Sorry.... we definitely need to catch up on PRs and issues... Notifications haven't been working so I keep on missing things.

**Comment by lanefu** [comment]
...and need to setup ci again

**Comment by adawalli** [comment]
Along these lines, will there be plans for continuing to tag releases? or should we just track `master`?

**Comment by lanefu** [comment]
Great question.. I'll have to investigate tagging and the previous release process. 

I know some of the other maintainers were having a bit of trouble updating ansible-galaxy with the other Hashicorp roles.

**Comment by bbaassssiiee** [comment]
I will push a tagged release when tests pass.

**Comment by rgarrigue** [comment]
Bumping the original question. Tried to install brianshumate.consul==v2.6.1 according to the latest release here, not found. Add to go for sources

```yml
- name: brianshumate.consul
  scm: git
  src: git@github.com:ansible-community/ansible-consul.git
  version: v2.6.1
```

**Comment by bbaassssiiee** [comment]
Brian transferred this to us because he has other things to do.

**Comment by rgarrigue** [comment]
@bbaassssiiee understood. But the original questions still stand:
- How do I install this, brianshumate.consul, or community.consul, or ? Please update the README.
- Do we track master ? Or will there be release ? The last release predate this issue.

**Comment by bbaassssiiee** [comment]
I added info in README.md
