### ISSUE TITLE
Consul Connect Should be allowed on any Server

### ISSUE THREAD

**Issue by adawalli** [ansible-collections/ansible-consul#400]
Currently, the template for config.json has the following logic

```
{% if (item.config_version != 'client') and consul_connect_enabled %}
```

This requires either a `bootstrap` or `server` node in order to utilize the Consul Connect technology. With the rise in technologies like Hashicorp's `Nomad`, `Connect` is used to provided a secured mesh network between **CLIENT** nodes. Allowing this only on "Server" no longer mistakes and isn't even compliant with Nomad architecture.

**Comment by lanefu** [comment]
Resolved by #401
