### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by buckeyze** [ansible-collections/ansible-consul#433]
I am really sorry for creating an issue but I am not sure how to ask a question to the contributors.  Someone can close this issue very soon once I get some feedback.  

I have been supporting consul enterprise for years and just discovered ansible-consul.  I already have datacenters (server nodes) deployed as well as hundreds of nodes running in client mode.  I mainly want to use ansible-consul to automate adding clients to the environment.  It appears like the role is an all-inclusive cluster and client node installation procedure.  

Is there an easy tweak to have it go out and acquire the encryption key and other items from a cluster node (server mode) and use it to build the configuration to install a client on a new VM?  Thank you.

**Comment by bbaassssiiee** [comment]
Not using this role, but feel free to steal from this task file:|
https://github.com/dockpack/consul-policies/blob/master/tasks/main.yml
