### ISSUE TITLE
issue with downloading files locally

### ISSUE THREAD

**Issue by jonhatalla** [ansible-collections/ansible-consul#50]
My control machine is a mac - downloading these files locally is causing errors with the get_url module.  

`fatal: [consul01]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for releases.hashicorp.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl"}
`

I have tried addressing the issue with what google returns, but haven't been able to get past this error.  I will issue a PR which should let all the file transferring occur on the remote host - which lets me get past it.

**Comment by brianshumate** [comment]
Hi Jon,

Not sure if you saw, but I mentioned some ideas over in #45:

>A pretty tedious way to work around this is to prefetch both the SHASUM file and the needed binary archive(s) (for both the remote hosts and your control host platforms) and place them into the files directory.

When I say prefetch the files, I mean you have to do so with something other than Ansible, like `curl` or a browser. It cannot be done with Ansible on a Mac at the moment as far as I know.

The role used to download from the remote hosts previously, but that is inefficient and wastes resources when you are using the role against a large number of nodes, so such a feature needs to be configureable as an alternative to the current approach.

**Comment by jonhatalla** [comment]
I see.

Will have a PR out shortly

**Comment by jonhatalla** [comment]
https://github.com/brianshumate/ansible-consul/pull/51
