### ISSUE TITLE
Support for consul validate

### ISSUE THREAD

**Issue by Lusitaniae** [ansible-collections/ansible-consul#518]
Ideally we'd have some validation task when updating template files

I'm trying something like this
`
    # validate: "consul validate %s {{ consul_configd_path }}"
`

Which fails with:
```
Config validation failed: Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.
```

Related to  https://github.com/hashicorp/consul/issues/3897?

**Comment by bastienwirtz** [comment]
Hello @Lusitaniae, 

Have you tried adding the main configuration file in the same command ? 
```sh
consul validate {{ consul_config_path }}/config.json {{ consul_configd_path }}
```
I just opened a PR to add the configuration validation (cf https://github.com/ansible-community/ansible-consul/pull/565).
