### ISSUE TITLE
bootstrap without bootstrap node

### ISSUE THREAD

**Issue by groggemans** [ansible-collections/ansible-consul#54]
If I read the info about the `-bootstrap-expect` option in the consul docs, I'm under the impression this is the better choice for normal clusters (not for testing that is).

As this doesn't require a node to be in bootstrap mode all the time, or restart it in normal server mode after bootstrapping. (something that's currently not done by this role, but would be good practice if I understand correctly)

I'd like to add an option to choose between both bootstrapping techniques.

What's your opinion on this @brianshumate?

**Comment by brianshumate** [comment]
Having bootstrap-expect set on one node is effectively all the bootstrap node_role does IIRC.

It used to be that leaving the bootstrap-expect option set was not advised, and so the role switched that off after the bootstrapping, but now there's not really a problem with leaving it in the configuration even after bootstrapping.

**Comment by brianshumate** [comment]
Oh, I forgot to mention that the role actually _used to_ restart the bootstrap node and enable the server configuration instead, but learned that it really was no longer necessary to remove bootstrap-expect even though Consul warns about it being enabled so I stopped doing that in the role.

We could add options to support having it and not having it though.

**Comment by groggemans** [comment]
I think your mixing up the `-bootstrap` and `-bootstrap-expect` options. But I get the point :)

Should we default to the current behavior with a bootstrap server? Or without one?

I'd personally prefer the version without one. Because this gives a more homogeneous setup. But I have no trouble defaulting to the version with a bootstrap server.
