### ISSUE TITLE
Check mode missing in one task

### ISSUE THREAD

**Issue by jstenvall-ducksify** [ansible-collections/ansible-consul#575]
Hello,

In the task `Create temporary file for raw gossip encryption key` in the file `nix.yml` check mode is missing. This task sets the variable `consul_raw_key_file`, and it must do so also in check mode, otherwise the following task fails: `Write gossip encryption key locally for use with new servers`

This is simple to fix by adding `check_mode: false` on line 111 in `nix.yml`.

Thanks a lot for your effort and support!

**Comment by nre-ableton** [comment]
Sure, no problem. See https://github.com/ansible-community/ansible-consul/pull/580.
