### ISSUE TITLE
Binary gets replaced each role run

### ISSUE THREAD

**Issue by jardleex** [ansible-collections/ansible-consul#60]
Hello @brianshumate,

first thanks for creating this role. Makes the first hands on consul much easier!

We're using ``consul_install_remotely: true`` and I've noticed that the consul binary gets replaced each time the role get's applied to the servers.
This is bit confusing for us as the installation is already done, so why replacing it each time? 
Mainly these tasks report a change on each run even when consul is already up and running:
- Read Consul package checksum
- Unarchive Consul and install binary (replaced the binary)

Also curious that the task _Cleanup_ in the end of _install_remote.yml_ does not trigger either.

May it be possible to alter the role so it performs the installation only if consul is absent?
Changing/replacing it when another version then installed is given via _consul_version_ might not be an good idea as a manual upgrade seems the safer way. 

Thank you very much!

Best regards

Jard

**Comment by brianshumate** [comment]
Hi Jard,

Thanks for the kind words. The role is mainly designed for bootstrapping new Consul clusters and does not do much to handle configuration of existing clusters so this would represent new functionality that will need some thinking before implementing.

**Comment by brianshumate** [comment]
Hi Jard,

Thanks again for your feedback. I've decided to implement a simple check for the binary and only include install or install_remote tasks when the binary is not present.
