### ISSUE TITLE
Fail if more then one bootstrap server is defined

### ISSUE THREAD

**Issue by vincent-legoll** [ansible-collections/ansible-consul#76]
I'm fairly new to ansible, and trying a simple ansible consul test install on VMs (3 * CentOS 7 on openstack)

The host launching the install has this:

$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

$ cat inventory.cfg
[consul]
192.168.1.200 consul_node_role=bootstrap
192.168.1.106 consul_node_role=server
192.168.1.103 consul_node_role=client

$ cat consul.yml
---

- hosts: consul
  roles:
    - ansible-consul

$ l -d roles/ansible-consul
drwxr-xr-x. 12 vlegoll users 4.0K Jun 23 14:18 roles/ansible-consul

This is a git clone of your repository, current master branch

$ ansible-playbook -i inventory.cfg consul.yml 
[...]
TASK [ansible-consul : Fail if more then one bootstrap server is defined] ********************************************************************************************************************
fatal: [192.168.1.200]: FAILED! => {"failed": true, "msg": "The conditional check '_consul_bootstrap_servers | length > 1' failed. The error was: error while evaluating conditional (_consul_bootstrap_servers | length > 1): {% set __consul_bootstrap_servers = [] %}{% for server in _consul_lan_servers %}{% set _consul_node_role = hostvars[server]['consul_node_role'] | default('client', true) %}{% if _consul_node_role == 'bootstrap' %}{% if __consul_bootstrap_servers.append(server) %}{% endif %}{% endif %}{% endfor %}{{ __consul_bootstrap_servers }}: {% set __consul_lan_servers = [] %}{% for server in consul_servers %}{% set _consul_datacenter = hostvars[server]['consul_datacenter'] | default('dc1', true) %}{% if _consul_datacenter == consul_datacenter %}{% if __consul_lan_servers.append(server) %}{% endif %}{% endif %}{% endfor %}{{ __consul_lan_servers }}: {% set _consul_servers = [] %}{% for host in groups[consul_group_name] %}{% set _consul_node_role = hostvars[host]['consul_node_role'] | default('client', true) %}{% if ( _consul_node_role == 'server' or _consul_node_role == 'bootstrap') %}{% if _consul_servers.append(host) %}{% endif %}{% endif %}{% endfor %}{{ _consul_servers }}: 'dict object' has no attribute u'cluster_nodes'\n\nThe error appears to have been in '/home/vlegoll/ansible/roles/ansible-consul/tasks/asserts.yml': line 68, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Fail if more then one bootstrap server is defined\n  ^ here\n"}

**Comment by brianshumate** [comment]
Hey there,

This is the same problem that was encountered in #74 and happens because you should not change the label name `[cluster_nodes]` in your hosts inventory to anything else.

It must be `[cluster_nodes]`.

I'll update the documentation to make an explicit note of this.

Thanks!

**Comment by groggemans** [comment]
@brianshumate @vincent-legoll 
You should be able to use a different group name by altering the `consul_group_name` variable.

But I think we should rename that variable to `consul_ansible_group` or something like that.

**Comment by groggemans** [comment]
@sobolevn see previous comment on how to properly fix your issue.

**Comment by sobolevn** [comment]
@groggemans thanks, but I have already fixed it.

**Comment by vincent-legoll** [comment]
OK, changing the group name to `[cluster_nodes]` fixes it. Thanks
