### ISSUE TITLE
Naming of repo should be brianshumate.consul

### ISSUE THREAD

**Issue by arehmandev** [ansible-collections/ansible-consul#84]
Hey Brian - the naming convention of your repo should be the same as that in Ansible-galaxy to avoid issues: e.g. brianshumate.consul instead of ansible-consul.

The reason I say this is that if anyone clones your repo via ansible-galaxy cli instead of git clone, the example wont work (    - { role: ansible-consul } is there instead of role: brianshumate.consull)

**Comment by groggemans** [comment]
Most role devs use the `ansible-rolename` or `ansible-role-name` convention for there repository names. Ansible galaxy should automatically handle this (even if you define git as source, just add the correct name).

```
- name: brianshumate.consul
  src: git@github.com:brianshumate/ansible-consul.git
  scm: git
```

When doing a manual git clone, you should provide the role name `brianshumate.consul` as a target dir.

**Comment by brianshumate** [comment]
Agreed with @groggemans here.

I am not aware of an `ansible-galaxy clone` command, but this role was designed to work with Ansible Galaxy and `ansible-galaxy install brianshumate.consul` works as expected.
