### ISSUE TITLE
Changing cluster_nodes to consul_cluster_nodes

### ISSUE THREAD

**Issue by jstoja** [ansible-collections/ansible-consul#94]
Hello Brian,

I'm currently using your roles for nomad and consul and I find it weird to have one role with `cluster_nodes` as a mandatory host group while having the nomad role with `nomad_cluster_nodes`.

This tiny issues makes it weird when using both on the same playbook (the inventory is then explicit for nomad but not for consul).

Do you think it would be possible to change this (I could make the PR if needed).

**Comment by brianshumate** [comment]
Hey there,

Thanks for the input; and I agree, it's poorly named throughout the projects.

I am not really a fan of the "nodes" naming convention at all, so I've renamed all references to *cluster_nodes* and *nomad_cluster_nodes* throughout the projects accordingly. They're now named:

- *consul_instances*
- *nomad_instances*
- *vault_instances*

Cheers!
